### ISSUE TITLE
Clear existing fills, but keep the styles.

### ISSUE THREAD

**Issue by RaphyRaph** [abynim/SketchSquares#12]
When you run the plugin on rectangle that already have a picture fill, it should replace it instead of adding on top of it.

**Comment by abynim** [comment]
@RaphyRaph the idea was to be non-destructive when adding image fills. So if you wanted to go back to a previously loaded image you could just by changing the fill. I see your point though, it could get cumbersome to manually delete the fills if you have even a dozen shapes with unwanted image fills.

**Comment by RaphyRaph** [comment]
Yeah, because I re-use squares, I sometimes have 6-7 stacks of unused fills.
