### ISSUE TITLE
Auth errors

### ISSUE THREAD

**Issue by mortocks** [abynim/SketchSquares#4]
The plugin kept failing with a console error
8/01/2015 5:09:55.222 pm CoreServicesUIAgent[4947]: Error -60005 creating authorization

I tried revoking access via instagram to then re-request access but the plugin still thinks it's authorised. Long term the plugin should re-check its auth status but in the short term, can I clear the apps "data" and if so, where is it stored? I tried deleting the plugin without success.

**Comment by abynim** [comment]
@mortocks Are you able to use the Logout option? That should clear all stored data. If you don't see the logout option, please make a `Logout.sketchplugin` file in the SketchSquares folder, add the following code in the file and run it from Sketch.

`#import 'library/communicator.js'  
sendJSONCommands({logout:true})`

Please let me know if it works for now. I will update the plugin to check auth status going forward. Thanks!

**Comment by abynim** [comment]
@mortocks just published a build with a check for auth status when a call is made to the Instagram API. If you've revoked access it should ask you to log in again. 

Please let me know if it works for you. Thanks for your help!

**Comment by mortocks** [comment]
Perfect - tested and working. That issue is resolved although the original problem seems to remain. I'll open an new issue

**Comment by abynim** [comment]
Sweet! Closing this one..
