### ISSUE TITLE
Broken in beta 3.3.2 (12041)

### ISSUE THREAD

**Issue by RaphyRaph** [abynim/SketchSquares#8]
The plugin doesn't seem to work on the beta.

**Comment by abynim** [comment]
@RaphyRaph the most recent released version is 3.3.2 (12043) and it seems to be working there. Please add some more details about your system. Are you on Yosemite? How far do you get with the plugin? Can you see the source selector, but it doesn't download images? Does it throw errors?

**Comment by RaphyRaph** [comment]
can't repro
